AWSTemplateFormatVersion: 2010-09-09
Description: |
    Deploys a barebone Wordpress deployment for as cheap as possible. 
Parameters:

    serverName:
      Description: DNS name of wordpress site
      Type: String
      Default: kgdevops.cloud

    serverAdminEmail:
      Description: Email to configure the web server with
      Type: String
      Default: kgdevops@gmail.com
    
    AutoScalingReplacingUpdate:
      Description: Whether or not to replace the Wordpress server on ASG update. WARNING! Leave this false unless you want your wordpress server possibly terminated. 
      Type: String
      AllowedValues:
        - true
        - false
      Default: false

    Subnets:
      Description: Possible subnets the wordpress server can be deployed in. Pick a minumum of 2
      Type: List<AWS::EC2::Subnet::Id>

    ASGMaxInstances: 
      Description: Max number of wordpress EC2 instances
      Type: Number
      Default: 1

    ASGMinInstances: 
      Description: Min number of wordpress EC2 instances
      Type: Number
      Default: 1

    VolumeSize: 
      Description: Min number of wordpress EC2 instances
      Type: Number
      Default: 10

    Key:
      Description: Keypair to use for the wordpress instances
      Type: AWS::EC2::KeyPair::KeyName

    InstanceType: 
      Description: Instance type to use for wordpress servers
      Type: String
      AllowedValues:
        - t3a.micro
        - t3a.nano
        - t2.micro
      Default: t2.micro

    AMI: 
      Description: Instance type to use for wordpress servers
      Type: AWS::EC2::Image::Id
      Default: ami-0c94855ba95c71c99

Resources:
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      DesiredCapacity: !Ref ASGMinInstances
      HealthCheckGracePeriod: 30
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: !Ref ASGMaxInstances
      MinSize: !Ref ASGMinInstances
      Tags:
          - Key: Name
            Value: WordpressBlog
            PropagateAtLaunch: true
          - Key: Project
            Value: Blog
            PropagateAtLaunch: true
      VPCZoneIdentifier: !Ref Subnets
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: !Ref AutoScalingReplacingUpdate

  LaunchConfiguration: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      KeyName: !Ref Key
      ImageId: !Ref AMI
      SecurityGroups: 
        - sg-0812211e5e9766213 #ToDo Create SG
      InstanceType: !Ref InstanceType
      IamInstanceProfile: arn:aws:iam::959398616823:role/WordPress-Blog-kgdevops-Role #ToDo create IAM Profile / Role
      BlockDeviceMappings: 
        - DeviceName: /dev/xvda 
          Ebs: 
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
      UserData: 
        Fn::Base64: !Sub |
          #!bin/bash
          sudo mkdir /testdir
          sudo touch /tmp/test
          echo serverAdminEmail: ${serverAdminEmail}  serverName: ${serverName} > /tmp/test
  
Outputs:
  AutoScalingGroup:
    Description: Autoscaling group containing the wordpress server/s
    Value: !Ref AutoScalingGroup